proxy: null
no_proxy: null
configs:
  use: "desktop"
  ubuntu:
    gui: true
    basebox: "bento/ubuntu-17.10"
    hostname: "ubuntu-desktop"
  desktop:
    gui: true
    basebox: "generic/fedora29"
    hostname: "fedora-desktop"
  server:
    gui: false
    basebox: "generic/centos7"
    hostname: "centos-server"
