---

- import_playbook: setup.yml

- name: install packages, create user, setup locale
  hosts: all
  gather_facts: yes
  become: yes
  become_user: root
  roles:
    - role: common
      tags: [ common ]
  vars_prompt:
    - name: username
      prompt: "Enter the desired username"
    - name: password
      prompt: "Enter the password to set for your user (omit to keep it)"
      confirm: yes
      private: yes
  tags: [ system ]

