---

- import_playbook: setup.yml

- name: install workstation
  hosts: all
  gather_facts: yes
  become: yes
  become_user: root
  roles:
    - role: git
      tags: [ git, server ]
    - role: zsh
      tags: [ zsh, server ]
    - role: tmux
      tags: [ tmux, server ]
    - role: powerline
      tags: [ powerline, server ]
    - role: executables
      tags: [ executables, server ]
    - role: vim
      tags: [ vim, server ]
#    - role: gnome
#      tags: [ gnome, gui ]
    - role: kde
      tags: [ kde, gui ]
    - role: onedrive
      tags: [ onedrive ]
  tags: [ workstation ]

