---

- name: install or update Zsh
  package:
    name: zsh
    state: latest
  tags:
    - packages
    - online

- import_role:
    name: dotfiles

- name: link imported Zsh configuration
  file:
    src: /home/{{ username }}/git/dotfiles/.zshrc
    path: /home/{{ username }}/.zshrc-{{ username }}
    state: link
    owner: "{{ username }}"
    group: "{{ username }}"
    force: yes
  tags:
    - dotfiles

- name: include imported Zsh configuration
  lineinfile:
    path: /home/{{ username }}/.zshrc
    line: "source ~/.zshrc-{{ username }}"
    create: yes
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0750
  tags:
    - configs

- name: download oh-my-zsh
  git:
    repo: "https://github.com/robbyrussell/oh-my-zsh.git"
    dest: /home/{{ username }}/git/oh-my-zsh
  become: yes
  become_user: "{{ username }}"
  tags:
    - git
    - online
    - oh-my-zsh

- name: set path to oh-my-zsh directory
  lineinfile:
    path: /home/{{ username }}/.zshrc-{{ username }}
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0750
  with_items:
    - regexp: "^export ZSH="
      line: "export ZSH=~/git/oh-my-zsh"
    - regexp: "^source \\$ZSH/"
      line: "source $ZSH/oh-my-zsh.sh"
  tags:
    - configs
    - oh-my-zsh

- name: set default shell for user {{ username }}
  user:
    name: "{{ username }}"
    shell: /bin/zsh
  tags:
    - user

