---

- name: install or update Docker from web
  shell: curl -fsSL get.docker.com | bash
  when: ansible_os_family != 'RedHat'
  notify:
    - restart Docker
  tags:
    - packages
    - online

- name: add Docker repository
  command: dnf config-manager --add-repo "https://download.docker.com/linux/{{ ansible_distribution|lower }}/docker-ce.repo"
  args:
    warn: false
  when: ansible_os_family == 'RedHat'
  tags:
    - packages
    - online

- name: install or update Docker from repository
  package:
    name: docker-ce
    state: latest
  when: ansible_os_family == 'RedHat'
  notify:
    - restart Docker
  tags:
    - packages
    - online

- name: add user {{ username }} to Docker group
  user:
    name: "{{ username }}"
    groups: docker
    append: yes
  tags:
    - user

- name: download releases metadata of Docker Compose
  uri:
    url: "https://api.github.com/repos/docker/compose/releases/latest"
    body_format: json
    return_content: yes
  register: docker_compose_releases
  tags:
    - scripts
    - online

- name: download Docker Compose
  get_url:
    url: "{{ item.browser_download_url }}"
    dest: /usr/local/bin/docker-compose
    mode: 0755
    force: yes
  when: item.browser_download_url.endswith('Linux-x86_64')
  with_items: "{{ docker_compose_releases.json.assets }}"
  tags:
    - scripts
    - online

- name: download bash completion for Docker Compose
  get_url:
    url: "https://raw.githubusercontent.com/docker/compose/master/contrib/completion/bash/docker-compose"
    dest: /etc/bash_completion.d/docker-compose
    mode: 0755
    force: yes
  tags:
    - scripts
    - online

